# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task --list
    silent: true

  package:
    desc: Package the extension
    cmds:
      - mkdir -p dist
      - zip -r dist/hn-comment-saver.zip * -x "*.DS_Store" -x ".git/*" -x ".gitignore" -x "node_modules/*" -x "package.json" -x "bun.lock" -x "dist/*"
      - echo "Extension packaged to dist/hn-comment-saver.zip"

  lint:
    desc: Lint the source with oxlint
    cmds:
      - bun run lint
